# database-pod.yaml
apiVersion: v1
kind: Pod
metadata:
  name: database-pod
  labels:
    app: my-app-label
spec:
  containers:
  - name: database-container
    image: your/database-image:tag
    # Add other necessary container configurations and ports as needed

