apiVersion: v1
kind: Pod
metadata:
  name: dns-pod
spec:
  containers:
  - name: dns-container
    image: busybox
    command: ["sleep", "3600"]  # Keep the pod running indefinitely
    stdin: true
    tty: true
  restartPolicy: Always

