apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    events { }
    http {
      upstream my-app-backend {
        server 10.244.1.2:8080;  # Replace with the actual IP of your pod
        server 10.244.1.3:8080;  # Add more backend servers as needed
        # Use the IP addresses of your existing poc-pod replicas
      }
      server {
        listen 80;
        location / {
          proxy_pass http://my-app-backend;
        }
      }
    }

